# Generated by Django 5.1 on 2024-08-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_work_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
