# Generated by Django 5.1 on 2024-08-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_industry_province_rename_location_work_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Hybrid', 'Hybrid'), ('Onsite', 'Onsite'), ('Remote', 'Remote')], max_length=50, null=True),
        ),
    ]
