# Generated by Django 5.1 on 2024-08-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_alter_applyjob_status_alter_work_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Hybrid', 'Hybrid'), ('Onsite', 'Onsite'), ('Remote', 'Remote')], max_length=50, null=True),
        ),
    ]
