# Generated by Django 5.1 on 2024-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_work_required_skills_alter_work_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='job_type',
            field=models.CharField(blank=True, choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('Onsite', 'Onsite')], max_length=50, null=True),
        ),
    ]
