# Generated by Django 5.1 on 2024-08-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_upload_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
