# Generated by Django 5.1 on 2024-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_resume_experience_level_resume_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Junior', 'Junior'), ('Associate', 'Associate'), ('Trainee', 'Trainee'), ('Mid Level', 'Mid Level'), ('Senior', 'Senior')], max_length=50, null=True),
        ),
    ]
